"""Standalone fallback UI for the ecommerce workspace.

This page intentionally has no Node.js dependency. It keeps the demo usable when
the optional Next.js development dependencies cannot be installed on Windows.
"""

ECOMMERCE_FALLBACK_HTML = r'''<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>DeerFlow · 电商选品研究工作台</title>
  <style>
    :root { color-scheme: dark; --bg:#08111f; --panel:#101d31; --line:#263955; --text:#edf5ff; --muted:#9db0c9; --accent:#63e6be; --blue:#79b8ff; --warn:#ffd166; }
    * { box-sizing:border-box; }
    body { margin:0; min-height:100vh; font-family:Segoe UI,Microsoft YaHei,sans-serif; color:var(--text); background:radial-gradient(circle at 10% 0%,#18375b 0,#08111f 42%,#050a12 100%); }
    .wrap { width:min(1180px,calc(100% - 32px)); margin:0 auto; padding:42px 0 80px; }
    .hero { display:flex; justify-content:space-between; gap:24px; align-items:end; margin-bottom:26px; }
    h1 { margin:0 0 10px; font-size:clamp(30px,5vw,54px); letter-spacing:-1px; }
    h2 { margin:0 0 14px; font-size:20px; } h3 { margin:0 0 8px; font-size:17px; }
    p { line-height:1.65; } .muted { color:var(--muted); }
    .eyebrow { color:var(--accent); text-transform:uppercase; letter-spacing:2px; font-size:12px; font-weight:700; }
    .panel { background:linear-gradient(145deg,rgba(20,37,61,.94),rgba(10,22,38,.94)); border:1px solid var(--line); border-radius:20px; padding:22px; box-shadow:0 18px 50px #0004; }
    .form { display:grid; grid-template-columns:repeat(4,1fr); gap:14px; } label { display:block; color:var(--muted); font-size:13px; margin-bottom:7px; }
    input,select { width:100%; color:var(--text); background:#091526; border:1px solid #345174; border-radius:10px; padding:11px 12px; font:inherit; outline:none; transition:border-color .2s,box-shadow .2s,transform .2s; } input:focus,select:focus { border-color:var(--accent); box-shadow:0 0 0 3px #63e6be22; }
    .wide { grid-column:span 2; } .actions { display:flex; align-items:center; justify-content:space-between; gap:14px; margin-top:16px; flex-wrap:wrap; }
    button { cursor:pointer; border:0; border-radius:10px; padding:12px 18px; background:linear-gradient(100deg,#4bd7b0,#78b9ff); color:#06131c; font-weight:800; font-size:15px; transition:transform .2s,filter .2s,box-shadow .2s; } button:hover:not(:disabled) { transform:translateY(-1px); filter:brightness(1.08); box-shadow:0 8px 22px #0005; } button:disabled { opacity:.5; cursor:wait; }
    button:focus-visible,input:focus-visible,select:focus-visible { outline:3px solid #63e6be88; outline-offset:2px; }
    .check { display:flex; align-items:center; gap:8px; color:var(--muted); } .check input { width:auto; }
    .status { min-height:24px; color:var(--muted); } .error { color:#ff8d8d; } .success { color:var(--accent); }
    .status-grid { display:grid; grid-template-columns:repeat(4,1fr); gap:10px; margin-top:14px; }
    .status-card { border:1px solid var(--line); border-radius:12px; padding:12px; background:#0b182b; }
    .status-card strong { display:block; margin-top:5px; color:var(--text); }
    .status-card.mock { border-color:#2f6e67; background:#0b2428; } .status-card.mock strong { color:var(--accent); }
    .status-card.live { border-color:#6c5a2a; background:#28230f; } .status-card.live strong { color:var(--warn); }
    .status-card.candidate { border-color:#376081; } .status-card.business { border-color:#75454d; background:#26171c; }
    .metrics { display:grid; grid-template-columns:repeat(4,1fr); gap:12px; margin:20px 0; } .metric { padding:16px; border:1px solid var(--line); border-radius:14px; background:#0b182b; } .metric strong { display:block; font-size:27px; margin-top:5px; color:var(--accent); }
    .grid { display:grid; grid-template-columns:repeat(3,1fr); gap:14px; } .rec { border:1px solid var(--line); border-radius:15px; padding:17px; background:#0a1729; } .score { color:var(--accent); font-size:26px; font-weight:800; float:right; }
    .bar { height:6px; background:#21334c; border-radius:9px; overflow:hidden; margin:7px 0 11px; } .bar i { display:block; height:100%; background:linear-gradient(90deg,var(--blue),var(--accent)); }
    .tag { display:inline-block; border:1px solid #376081; border-radius:99px; color:#b9d6f4; padding:3px 8px; margin:3px 4px 0 0; font-size:12px; }
    .evidence { margin-top:20px; } .evidence-item { padding:12px 0; border-bottom:1px solid #20314a; } a { color:var(--blue); } .download { display:flex; gap:8px; flex-wrap:wrap; } .download button { background:#172c48; color:#dbeaff; font-size:13px; padding:9px 12px; }
    .toolbar { display:grid; grid-template-columns:1fr 1fr; gap:20px; margin-top:20px; } .toolbar .panel { min-height:180px; }
    table { width:100%; border-collapse:collapse; font-size:12px; } th,td { text-align:left; padding:8px; border-bottom:1px solid #20314a; white-space:nowrap; max-width:220px; overflow:hidden; text-overflow:ellipsis; }
    .history-row { display:flex; align-items:center; gap:8px; padding:9px 0; border-bottom:1px solid #20314a; } .history-row button { padding:6px 9px; font-size:12px; background:#172c48; color:#dbeaff; } .history-row .grow { flex:1; min-width:0; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; }
    .progress { margin-top:16px; } .progress-track { height:7px; border-radius:9px; background:#20314a; overflow:hidden; } .progress-track i { display:block; height:100%; width:55%; background:linear-gradient(90deg,var(--blue),var(--accent)); animation:pulse 1.4s ease-in-out infinite alternate; } @keyframes pulse { from { opacity:.55; transform:translateX(-20%); } to { opacity:1; transform:translateX(70%); } }
    .stage-rail { display:grid; grid-template-columns:repeat(4,1fr); gap:8px; margin-top:14px; } .stage { padding:8px 10px; border:1px solid var(--line); border-radius:10px; color:#7186a4; font-size:12px; transition:all .2s; } .stage.active { color:var(--text); border-color:var(--blue); background:#193253; } .stage.done { color:var(--accent); border-color:#2f6e67; }
    .decision-grid { display:grid; grid-template-columns:1.2fr 1fr; gap:12px; margin-top:14px; } .decision-card { padding:14px; border:1px solid #365471; border-radius:14px; background:#0b1b30; } .decision-card strong { display:block; color:var(--accent); font-size:18px; margin-top:4px; } .quality-grid { display:flex; flex-wrap:wrap; gap:6px; margin-top:8px; } .quality-pill { border:1px solid #376081; border-radius:99px; padding:4px 8px; font-size:11px; color:#b9d6f4; }
    .hidden { display:none; } .notice { margin-top:14px; padding:12px 14px; border-left:3px solid var(--warn); background:#342c1544; color:#ffe9a8; }
    .section-grid { display:grid; grid-template-columns:repeat(2,1fr); gap:12px; margin-top:14px; }
    .section-card { border:1px solid var(--line); border-radius:14px; padding:14px; background:#0b182b; min-width:0; }
    .section-card h3 { color:var(--blue); } .section-card p { margin:7px 0 0; }
    @media(max-width:800px){ .hero{display:block}.form,.metrics,.grid,.status-grid{grid-template-columns:1fr 1fr}.wide{grid-column:span 2} .section-grid{grid-template-columns:1fr} } @media(max-width:520px){ .form,.metrics,.grid,.status-grid{grid-template-columns:1fr}.wide{grid-column:auto} }
  </style>
</head>
<body>
<main class="wrap">
  <div class="hero"><div><div class="eyebrow">DeerFlow · Ecommerce Research</div><h1>电商选品研究工作台</h1><p class="muted">用 Mock 数据快速演示完整流程；切换 Live + DeepSeek 后可接入真实搜索与模型。</p></div><div class="tag">Python fallback UI</div></div>
  <section class="panel">
    <h2>研究参数</h2>
    <div class="form">
      <div class="wide"><label for="category">商品品类</label><input id="category" value="可折叠露营桌" /></div>
      <div><label for="market">研究市场</label><input id="market" value="中国大陆电商" /></div>
      <div><label for="customer">目标客群（可选）</label><input id="customer" placeholder="例如：年轻上班族" /></div>
      <div><label for="min">搜索筛选最低价格（元）</label><input id="min" type="number" value="99" /></div>
      <div><label for="max">搜索筛选最高价格（元）</label><input id="max" type="number" value="299" /></div>
      <div><label for="mode">数据模式</label><select id="mode"><option value="mock">Mock 离线演示</option><option value="live">Live 真实搜索</option></select></div>
      <div><label for="model">模型</label><select id="model"><option value="mock">Mock 模型</option><option value="deepseek">DeepSeek</option></select></div>
    </div>
    <p class="muted">价格区间仅用于搜索筛选，不是最终推荐价带；最终价格会结合竞品价格锚点重新计算。</p>
    <div class="actions"><label class="check"><input id="parallel" type="checkbox" checked /> 并行执行搜索模块</label><button id="run">开始生成选品报告</button><span id="status" class="status" role="status" aria-live="polite"></span></div>
    <div id="progress" class="progress hidden" aria-live="polite"><div id="progressText" class="muted">准备研究参数</div><div class="progress-track"><i></i></div><div class="stage-rail"><div class="stage active" data-stage="0">01 参数</div><div class="stage" data-stage="1">02 搜索</div><div class="stage" data-stage="2">03 清洗</div><div class="stage" data-stage="3">04 报告</div></div></div>
  </section>
  <section class="toolbar">
    <section class="panel"><h2>Excel 数据预览与导入</h2><p class="muted">先预览和调整字段映射，再绑定当前报告进行校验；确认后才写入本地审计快照。</p><input id="excelFile" type="file" accept=".xlsx,.xlsm,.xls,.csv,.tsv" /><div id="excelStatus" class="status"></div><div id="excelPreview" class="evidence-item hidden"></div><div id="excelMapping" class="evidence-item hidden"></div><div class="download"><button id="validateExcel" disabled>校验当前映射</button><button id="importExcel" disabled>确认导入当前报告</button></div></section>
    <section class="panel"><div class="actions"><div><h2>历史报告</h2><p class="muted">保存于本地 SQLite；回放不会重复调用搜索或模型。</p></div><button id="compare">对比所选</button></div><div id="historyList" class="muted">完成一次研究后会显示历史记录。</div><div id="comparison" class="evidence-item hidden"></div></section>
  </section>
  <section id="result" class="hidden">
    <div class="metrics"><div class="metric"><span class="muted">综合评分</span><strong id="total">-</strong></div><div class="metric"><span class="muted">推荐方向</span><strong id="recCount">-</strong></div><div class="metric"><span class="muted">候选证据</span><strong id="candidateCount">-</strong></div><div class="metric"><span class="muted">运行耗时</span><strong id="latency">-</strong></div></div>
    <section class="panel"><div class="actions"><div><h2 id="title">研究报告</h2><p id="summary" class="muted"></p></div><div class="download"><button data-download="json">下载 JSON</button><button data-download="markdown">下载 Markdown</button><button data-download="html">下载 HTML</button></div></div><div id="decision"></div><div id="warnings"></div><div id="qualitySummary" class="status-grid"></div></section>
    <section class="panel evidence"><h2>五大报告板块</h2><p class="muted">结构化展示研究结论；候选证据不会自动升级为商业事实。</p><div id="reportSections" class="section-grid"></div></section>
    <section class="panel evidence"><h2>推荐方向</h2><div id="recommendations" class="grid"></div></section>
    <section class="panel evidence"><h2>搜索过程与来源质量</h2><div id="searchDetails" class="grid"></div></section>
    <section class="panel evidence"><h2>候选证据目录</h2><div id="candidates"></div></section>
  </section>
</main>
<script>
const $ = (id) => document.getElementById(id);
let latest = null;
let historyRows = [];
let excelFile = null;
let excelMapping = {};
let progressTimer = null;
const workspaceKey = 'deerflow-ecommerce-workspace';
const workspaceId = localStorage.getItem(workspaceKey) || (globalThis.crypto?.randomUUID?.() || `local-${Date.now()}`);
localStorage.setItem(workspaceKey, workspaceId);
const esc = (v) => String(v ?? '').replace(/[&<>"']/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const scoreBar = (label, value) => `<div class="muted">${esc(label)} · ${Number(value || 0).toFixed(1)}</div><div class="bar"><i style="width:${Math.max(0, Math.min(100, Number(value || 0)))}%"></i></div>`;
function startProgress() { const steps = ['校验研究参数','执行搜索模块','整理来源与价格','生成评分与报告']; let index = 0; $('progress').classList.remove('hidden'); $('progressText').textContent = steps[0]; document.querySelectorAll('[data-stage]').forEach((node) => node.classList.toggle('active', node.dataset.stage === '0')); progressTimer = setInterval(() => { index = Math.min(index + 1, steps.length - 1); $('progressText').textContent = steps[index]; document.querySelectorAll('[data-stage]').forEach((node) => { const stage = Number(node.dataset.stage); node.classList.toggle('active', stage === index); node.classList.toggle('done', stage < index); }); }, 1500); }
function stopProgress() { if (progressTimer) clearInterval(progressTimer); progressTimer = null; $('progress').classList.add('hidden'); }
function renderSearchDetails(details) { const source = details?.module_status || details || {}; const entries = Object.entries(source).filter(([, value]) => value && typeof value === 'object'); $('searchDetails').innerHTML = entries.length ? entries.map(([name, value]) => { const anchors = Array.isArray(value.price_anchor_values) && value.price_anchor_values.length ? ` · 锚点：${value.price_anchor_values.map((price) => `¥${Number(price).toFixed(0)}`).join(' / ')}` : ''; const quality = value.source_quality_score != null ? ` · 来源质量：${Number(value.source_quality_score).toFixed(2)}` : ''; return `<article class="rec"><h3>${esc(name)}</h3><p class="muted">状态：${esc(value.status || 'unknown')} · 结果：${value.result_count ?? value.returned_count ?? '-'} · 已提价：${value.priced_result_count ?? '-'}</p><p class="muted">清洗重复：${value.cleaned_duplicate_count ?? 0} · 低分过滤：${value.filtered_low_score_count ?? 0}${quality}</p>${anchors ? `<p class="tag">${anchors.slice(3)}</p>` : ''}</article>`; }).join('') : '<p class="muted">当前模式未返回搜索模块明细。</p>'; }
async function loadHistory() { const response = await fetch('/api/ecommerce/history', {headers:{'X-Workspace-Id':workspaceId}}); if (!response.ok) return; const payload = await response.json(); historyRows = payload.reports || []; $('historyList').innerHTML = historyRows.length ? historyRows.slice(0,8).map((item) => `<div class="history-row"><input type="checkbox" data-history-check value="${esc(item.history_id)}" /><button class="grow" data-replay="${esc(item.history_id)}">${esc(item.category)}</button><span>${Number(item.average_score || 0).toFixed(1)}</span></div>`).join('') : '<span class="muted">完成一次研究后会显示历史记录。</span>'; document.querySelectorAll('[data-replay]').forEach((button) => button.addEventListener('click', () => replayReport(button.dataset.replay))); }
async function replayReport(id) { $('status').textContent = '正在回放历史报告…'; try { const response = await fetch(`/api/ecommerce/history/${encodeURIComponent(id)}/replay`, {method:'POST',headers:{'X-Workspace-Id':workspaceId}}); const data = await response.json(); if (!response.ok) throw new Error(data.detail || '报告回放失败'); render(data); $('status').textContent = '回放完成 · 未调用搜索或模型 API'; } catch (error) { $('status').textContent = error.message; $('status').className = 'status error'; } }
async function previewExcel(file) { excelFile = file; $('excelStatus').textContent = '正在读取文件…'; $('excelStatus').className = 'status'; const form = new FormData(); form.append('file', file); try { const response = await fetch('/api/ecommerce/excel/preview', {method:'POST',body:form}); const data = await response.json(); if (!response.ok) throw new Error(data.detail || 'Excel 预览失败'); const preview = data.preview; excelMapping = {...(preview.column_mapping || {})}; $('excelPreview').classList.remove('hidden'); $('excelPreview').innerHTML = `<strong>${esc(data.filename)}</strong><p class="muted">${preview.row_count} 行 · ${esc(preview.status)} · 列：${preview.columns.map(esc).join('、')}</p>${preview.missing_required_columns.length ? `<div class="notice">缺少必需列：${preview.missing_required_columns.map(esc).join('、')}</div>` : ''}<div style="overflow:auto"><table><thead><tr>${preview.columns.slice(0,8).map((column) => `<th>${esc(column)}</th>`).join('')}</tr></thead><tbody>${preview.preview_rows.slice(0,3).map((row) => `<tr>${preview.columns.slice(0,8).map((column) => `<td>${esc(row[column])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`; renderExcelMapping(preview); $('excelStatus').textContent = '预览完成'; } catch (error) { $('excelStatus').textContent = error.message; $('excelStatus').className = 'status error'; } }
function renderExcelMapping(preview) { const fields = preview.required_fields || []; $('excelMapping').classList.remove('hidden'); $('excelMapping').innerHTML = `<strong>字段映射</strong><p class="muted">自动匹配可手动修正，当前报告生成后才能校验。</p><div class="form">${fields.map((field) => `<label>${esc(field)}<select data-map-field="${esc(field)}"><option value="">未映射</option>${(preview.mapping_options?.[field] || []).filter(Boolean).map((column) => `<option value="${esc(column)}" ${excelMapping[field] === column ? 'selected' : ''}>${esc(column)}</option>`).join('')}</select></label>`).join('')}</div>`; document.querySelectorAll('[data-map-field]').forEach((select) => select.addEventListener('change', () => { excelMapping[select.dataset.mapField] = select.value; })); }
async function validateExcel() { if (!excelFile || !latest?.history_id) { $('excelStatus').textContent = '请先生成报告并选择 Excel 文件。'; $('excelStatus').className = 'status error'; return; } const form = new FormData(); form.append('file', excelFile); form.append('report_id', latest.history_id); form.append('mapping_json', JSON.stringify(excelMapping)); $('excelStatus').textContent = '正在校验字段映射和数据质量…'; const response = await fetch('/api/ecommerce/excel/validate', {method:'POST',headers:{'X-Workspace-Id':workspaceId},body:form}); const data = await response.json(); if (!response.ok) throw new Error(data.detail || 'Excel 校验失败'); latest.excel_validation = data.validation; $('excelStatus').textContent = data.status === 'success' ? '校验通过，可确认导入。' : `校验未通过：${(data.validation.errors || []).join('；')}`; $('importExcel').disabled = data.status !== 'success'; }
async function importExcel() { if (!excelFile || !latest?.history_id) return; const form = new FormData(); form.append('file', excelFile); form.append('report_id', latest.history_id); form.append('mapping_json', JSON.stringify(excelMapping)); form.append('confirm', 'true'); $('excelStatus').textContent = '正在写入本地导入审计快照…'; const response = await fetch('/api/ecommerce/excel/import', {method:'POST',headers:{'X-Workspace-Id':workspaceId},body:form}); const data = await response.json(); if (!response.ok) throw new Error(data.detail?.message || data.detail || 'Excel 导入失败'); $('excelStatus').textContent = `导入成功：${data.imported_count || 0} 行，已保存本地审计快照。`; }
function download(kind) { if (!latest) return; const body = kind === 'json' ? JSON.stringify(latest, null, 2) : (kind === 'markdown' ? latest.report_markdown : latest.report_html); const type = kind === 'json' ? 'application/json' : 'text/plain'; const blob = new Blob([body], {type}); const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = `ecommerce-report.${kind === 'json' ? 'json' : kind === 'markdown' ? 'md' : 'html'}`; a.click(); URL.revokeObjectURL(a.href); }
function render(data) {
  latest = data; const report = data.report || {}; const recs = report.recommendations || []; const candidates = (data.candidate_catalog || {}).candidates || [];
  $('result').classList.remove('hidden'); $('total').textContent = recs.length ? Number(recs.reduce((s,r) => s + Number(r.score?.total || 0), 0) / recs.length).toFixed(1) : '-'; $('recCount').textContent = recs.length; $('candidateCount').textContent = candidates.length; $('latency').textContent = `${Number(data.metrics?.latency_ms || 0).toFixed(0)} ms`; $('title').textContent = `研究报告：${report.request?.category || ''}`; $('summary').textContent = report.executive_summary || '报告已生成。';
  const gates = data.report_quality_gates || data.metrics?.report_quality_gates || {}; const topAction = report.next_actions?.[0] || '先补齐验证卡片中的商业数据'; $('decision').innerHTML = `<div class="decision-grid"><div class="decision-card"><span class="muted">当前决策状态</span><strong>${esc(report.decision_status || 'validate_first')}</strong><p>${esc(report.decision_basis || '')}</p></div><div class="decision-card"><span class="muted">下一步最重要动作</span><strong>先验证</strong><p>${esc(topAction)}</p></div></div><div class="evidence-item"><strong>研究进度事件</strong>${(data.progress_events || []).map((event) => `<div class="tag">${esc(event.stage)} · ${esc(event.status)} · ${esc(event.message)}</div>`).join('')}</div><div class="evidence-item"><strong>报告质量门禁</strong><div class="quality-grid">${Object.entries(gates).map(([name, passed]) => `<span class="quality-pill">${esc(name)}：${passed ? '通过' : '待补齐'}</span>`).join('')}</div></div>`;
  $('warnings').innerHTML = (report.warnings || []).map((w) => `<div class="notice">${esc(w)}</div>`).join('');
  const quality = data.quality_audit || {}; const searchStatus = data.search_status || 'unknown'; const modelStatus = data.model_status || 'unknown';
  $('qualitySummary').innerHTML = `<div class="status-card ${searchStatus === 'mock' ? 'mock' : 'live'}"><span class="muted">搜索模式</span><strong>${esc(searchStatus === 'mock' ? 'Mock 离线' : searchStatus)}</strong></div><div class="status-card ${modelStatus === 'mock' ? 'mock' : 'live'}"><span class="muted">模型模式</span><strong>${esc(modelStatus === 'mock' ? 'Mock 结构化' : modelStatus)}</strong></div><div class="status-card candidate"><span class="muted">证据边界</span><strong>${esc(quality.status || 'candidate_only')}</strong></div><div class="status-card business"><span class="muted">商业决策</span><strong>${quality.commercial_decision_ready ? '已通过' : '需人工核验'}</strong><small class="muted">Trace ${esc(data.trace_id || '未记录')}</small></div>`;
  const trends = report.trends || []; const competitors = report.competitors || []; const profiles = report.customer_profiles || []; const risks = report.opportunities_risks || [];
  $('reportSections').innerHTML = `<article id="report-section-market" class="section-card"><h3>一、市场趋势</h3>${trends.length ? trends.map((item) => `<p><strong>${esc(item.name)}</strong>：${esc(item.rationale)}<br><span class="tag">${esc(item.direction)} · 需求 ${Number(item.demand_score || 0).toFixed(0)}</span></p>`).join('') : '<p class="muted">暂无趋势信号。</p>'}</article><article id="report-section-competitive" class="section-card"><h3>二、竞品与价格</h3>${competitors.length ? competitors.map((item) => `<p><strong>${esc(item.name)}</strong>：¥${Number(item.price || 0).toFixed(0)} · ${esc(item.positioning)}</p>`).join('') : '<p class="muted">暂无竞品数据。</p>'}</article><article id="report-section-customer" class="section-card"><h3>三、目标人群匹配</h3>${profiles.length ? profiles.map((item) => `<p><strong>${esc(item.segment)}</strong>：需求 ${esc((item.needs || []).join('、'))}；痛点 ${esc((item.pain_points || []).join('、'))}</p>`).join('') : '<p class="muted">暂无客群画像。</p>'}</article><article id="report-section-risk" class="section-card"><h3>四、风险与进入壁垒</h3>${risks.length ? risks.map((item) => `<p><strong>风险 ${Number(item.risk_score || 0).toFixed(0)}</strong>：${esc((item.risks || []).join('；'))}<br><span class="muted">缓解：${esc((item.mitigations || []).join('；'))}</span></p>`).join('') : '<p class="muted">暂无风险评估。</p>'}</article><article id="report-section-action" class="section-card"><h3>五、推荐方向与验证动作</h3>${recs.length ? recs.map((item) => `<p><strong>${esc(item.product_name)}</strong> · ${esc(item.price_range)}<br><span class="muted">验证：${esc(item.validation_action || '补充验证')}；阈值：${esc(item.validation_threshold || '待补齐')}</span></p>`).join('') : '<p class="muted">暂无推荐方向。</p>'}</article>`;
  $('recommendations').innerHTML = recs.map((r) => `<article class="rec"><span class="score">${Number(r.score?.total || 0).toFixed(1)}</span><h3>${esc(r.product_name)}</h3><p class="muted">${esc(r.positioning)}</p><div class="tag">${esc(r.price_range)}</div><p class="muted">价格依据：${esc(r.price_basis || '未提供')}</p>${scoreBar('需求',r.score?.demand)}${scoreBar('竞争',r.score?.competition)}${scoreBar('利润',r.score?.margin)}${scoreBar('差异化',r.score?.differentiation)}<p>${esc(r.rationale)}</p><div class="notice"><strong>验证卡片</strong><br>动作：${esc(r.validation_action || '补充验证')}<br>成功阈值：${esc(r.validation_threshold || '补充可量化阈值')}<br>需要补齐：${esc((r.validation_data_needed || []).join('、'))}<br>未达标处理：${esc(r.validation_failure_action || '暂停扩大库存')}</div><small class="muted">${esc(r.score_note || '')}</small></article>`).join('');
  $('validateExcel').disabled = !data.history_id;
  renderSearchDetails(data.search_details);
  $('candidates').innerHTML = candidates.length ? candidates.map((c) => `<div class="evidence-item"><h3>${esc(c.title)}</h3><div class="muted">来源质量：${esc(c.source_quality_category)} · 候选排序：${Number(c.candidate_rank_score || 0).toFixed(2)} · 证据数：${c.evidence_count || 0}</div><p>${(c.modules || []).map((m) => `<span class="tag">${esc(m)}</span>`).join('')}</p><a href="${esc(c.source_url)}" target="_blank" rel="noreferrer">打开来源</a></div>`).join('') : '<p class="muted">当前报告没有候选证据。</p>';
}
 $('run').addEventListener('click', async () => { $('run').disabled = true; $('status').textContent = '正在生成报告，请稍候…'; $('status').className = 'status'; startProgress(); try { const payload = {category:$('category').value.trim(), market:$('market').value.trim(), customer:$('customer').value.trim() || null, price_min:Number($('min').value || 0), price_max:Number($('max').value || 0), mode:$('mode').value, model:$('model').value, search_parallel:$('parallel').checked, search_timeout:20, search_retries:2}; const resp = await fetch('/api/ecommerce/research',{method:'POST',headers:{'Content-Type':'application/json','X-Workspace-Id':workspaceId},body:JSON.stringify(payload)}); const data = await resp.json(); if (!resp.ok) throw new Error(data.detail || '研究请求失败'); render(data); await loadHistory(); $('status').textContent = `完成 · 搜索：${data.search_status} · 模型：${data.model_status}`; } catch (e) { $('status').textContent = e.message; $('status').className = 'status error'; } finally { stopProgress(); $('run').disabled = false; } });
 $('excelFile').addEventListener('change', (event) => { const file = event.target.files?.[0]; if (file) void previewExcel(file); });
 $('validateExcel').addEventListener('click', () => void validateExcel().catch((error) => { $('excelStatus').textContent = error.message; $('excelStatus').className = 'status error'; }));
 $('importExcel').addEventListener('click', () => void importExcel().catch((error) => { $('excelStatus').textContent = error.message; $('excelStatus').className = 'status error'; }));
 $('compare').addEventListener('click', async () => { const ids = [...document.querySelectorAll('[data-history-check]:checked')].map((input) => input.value); if (ids.length < 2) { $('status').textContent = '请选择至少两个历史报告进行对比'; $('status').className = 'status error'; return; } const response = await fetch('/api/ecommerce/compare', {method:'POST',headers:{'Content-Type':'application/json','X-Workspace-Id':workspaceId},body:JSON.stringify({report_ids:ids})}); const data = await response.json(); if (!response.ok) { $('status').textContent = data.detail || '报告对比失败'; $('status').className = 'status error'; return; } $('comparison').classList.remove('hidden'); $('comparison').innerHTML = `<strong>对比结果</strong><table><thead><tr><th>品类</th><th>平均分</th><th>推荐数</th><th>候选证据</th></tr></thead><tbody>${(data.rows || []).map((row) => `<tr><td>${esc(row.category)}</td><td>${Number(row.average_score || 0).toFixed(1)}</td><td>${row.recommendation_count}</td><td>${row.candidate_count}</td></tr>`).join('')}</tbody></table>`; });
document.querySelectorAll('[data-download]').forEach((b) => b.addEventListener('click', () => download(b.dataset.download)));
loadHistory();
</script>
</body></html>'''
